CREATE DATABASE TiendaVideoJuegosIUE

USE TiendaVideoJuegosIUE
GO

CREATE TABLE Pais(
	Id INT IDENTITY(1, 1) NOT NULL,
	Nombre VARCHAR(100) NOT NULL,
	CodigoAlfa VARCHAR(5) NOT NULL,
	Indicativo INT NULL,
	CONSTRAINT pkPais PRIMARY KEY (Id)
)
GO

CREATE TABLE Region(
	Id INT IDENTITY(1, 1) NOT NULL,
	Nombre VARCHAR(100) NOT NULL,
	Codigo VARCHAR(10) NOT NULL,
	IdPais INT NOT NULL,
	CONSTRAINT pkRegion PRIMARY KEY (Id),
	CONSTRAINT fkRegion_Pais FOREIGN KEY (IdPais) REFERENCES Pais(Id)
)

CREATE TABLE Ciudad(
	Id INT IDENTITY(1, 1) NOT NULL,
	Nombre VARCHAR(100) NOT NULL,
	IdRegion INT NOT NULL,
	CONSTRAINT pkCiudad PRIMARY KEY (Id),
	CONSTRAINT fkCiudad_Region FOREIGN KEY (IdRegion) REFERENCES Region(Id)
)

CREATE TABLE Titulo(
	
)

